---
danhoerst:
  status:
    - employee
  title: GitHub
  manager: mrsbworth
grantbirki:
  status:
    - employee
  title: GitHub
  manager: mrsbworth
andregce:
  status:
    - employee
  title: GitHub
  manager: mrsbworth
